// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('./src/components/atoms/AButton.vue')['default']
    ACard: typeof import('./src/components/atoms/ACard.vue')['default']
    ADropdown: typeof import('./src/components/atoms/ADropdown.vue')['default']
    AListItem: typeof import('./src/components/atoms/AListItem.vue')['default']
    ANumberInput: typeof import('./src/components/atoms/ANumberInput.vue')['default']
    DropdownMenu: typeof import('./src/components/molecules/DropdownMenu.vue')['default']
    ElInputNumbe: typeof import('element-plus/es')['ElInputNumbe']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    Header: typeof import('./src/components/organisms/Header.vue')['default']
    LabelButton: typeof import('./src/components/molecules/LabelButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchWrapper: typeof import('./src/components/molecules/SearchWrapper.vue')['default']
    TextField: typeof import('./src/components/atoms/TextField.vue')['default']
    YoutubePlayer: typeof import('./src/components/atoms/YoutubePlayer.vue')['default']
  }
}

export {}
