export interface IPlayerVars {
  autoplay?: 0 | 1 | undefined,
  cc_lang_pref?: string | undefined,
  cc_load_policy?: 1 | undefined,
  color?: 'red' | 'white' | undefined,
  controls?: 0 | 1 | undefined,
  disablekb?: 0 | 1 | undefined,
  enablejsapi?: 0 | 1 | undefined,
  end?: number | undefined,
  fs?: 0 | 1 | undefined,
  hl?: string | undefined,
  iv_load_policy?: 1 | 3 | undefined,
  list?: string | undefined,
  listType?: 'playlist' | 'search' | 'user_uploads' | undefined,
  loop?: 0 | 1 | undefined,
  modestbranding?: 1 | undefined,
  origin?: string | undefined,
  playlist?: string | undefined,
  playsinline?: 0 | 1 | undefined,
  rel?: 0 | 1 | undefined,
  start?: number | undefined,
  widget_referrer?: string | undefined,
}
